version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nmit

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine

    container_name: redis

    restart: always

    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management

    container_name: rabbitmq

    restart: always

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build:
      context: ./nmit

    container_name: backend

    depends_on:
      - mysql
      - redis
      - rabbitmq

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nmit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

      JWT_SECRET: VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVGVzdGluZzEyMzQ1Njc4OTA=

      SPRING_MAIL_USERNAME: abhijithravi2005@gmail.com
      SPRING_MAIL_PASSWORD: ciiq dyld dfaw yktr

      RAZORPAY_KEY_ID: rzp_test_TG9nmAc193JmcT
      RAZORPAY_KEY_SECRET: g8YwIqTynIF03S2JQawjBdDq

  frontend:
    build:
      context: ./GDG-FRONTEND

    container_name: frontend

    depends_on:
      - backend

    ports:
      - "5173:5173"

volumes:
  mysql-data: