spring.application.name=nmit
# MySQL Database Connection Details
spring.datasource.url=jdbc:mysql://localhost:3306/nmit
spring.datasource.username=root
spring.datasource.password=root
spring.security.enabled=false

# jwt details
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUVGVzdGluZzEyMzQ1Njc4OTA=
jwt.expiration=86400000

# logging details
logging.level.root=WARN
logging.level.com.gdg.nmit=DEBUG
logging.file.name=logs/event-management.log

# Redis details
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RabbitMQ details
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# mail service 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhijithravi2005@gmail.com
spring.mail.password=ciiq dyld dfaw yktr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# payment service
razorpay.key.id=rzp_test_TG9nmAc193JmcT
razorpay.key.secret=g8YwIqTynIF03S2JQawjBdDq